"use client";

import NextImage from "next/image";
import { type ComponentProps, useMemo, useState } from "react";
import { Check, ChevronRight, CreditCard, Menu, MessageCircle, Minus, Plus, ShieldCheck, ShoppingBag, Store, X } from "lucide-react";

const whatsappNumber = "573006160613";
const paymentLink = "https://checkout.nequi.wompi.co/l/Z801LL";
function Image(props: ComponentProps<typeof NextImage>) {
  return <NextImage {...props} unoptimized />;
}
const products = [
  { id: "premium-340", name: "Granola Premium", size: "Tarro 340 g", price: 22000, image: "/products/granola-premium-340g.webp", note: "Práctica, crocante y lista para disfrutar." },
  { id: "clasica-500", name: "Granola Nutrimax Clásica", size: "Bolsa 500 g", price: 22000, image: "/products/granola-bowl.webp", note: "La presentación ideal para tu desayuno diario." },
  { id: "clasica-1500", name: "Granola Clásica", size: "Bolsa 1.500 g", price: 45000, image: "/products/granola-clasica-1500g.webp", note: "Más cantidad para compartir en familia." },
  { id: "gourmet-1500", name: "Granola Gourmet", size: "Bolsa 1.500 g", price: 60000, image: "/products/granola-gourmet-1500g.webp", note: "Una mezcla especial con ingredientes seleccionados." },
  { id: "dietetica-500", name: "Granola Nutrimax Dietética", size: "Bolsa 500 g", price: 25000, image: "/products/granola-bowl.webp", note: "Sin panela ni uvas pasas. Con más almendras y sin azúcares añadidos." },
] as const;
const money = new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 });

export default function Home() {
  const [cart, setCart] = useState<Record<string, number>>({});
  const [cartOpen, setCartOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const items = products.filter((product) => (cart[product.id] ?? 0) > 0);
  const quantity = Object.values(cart).reduce((sum, value) => sum + value, 0);
  const total = useMemo(() => products.reduce((sum, product) => sum + product.price * (cart[product.id] ?? 0), 0), [cart]);
  const change = (id: string, amount: number) => setCart((current) => ({ ...current, [id]: Math.max(0, (current[id] ?? 0) + amount) }));

  function sendWhatsApp() {
    const lines = items.map((product) => `• ${cart[product.id]} x ${product.name} ${product.size} — ${money.format(product.price * cart[product.id])}`);
    const message = ["Hola, Alimentos Nutrimax. Quiero realizar este pedido:", "", ...lines, "", `Total de productos: ${money.format(total)}`, "Deseo confirmar disponibilidad y valor del envío."].join("\n");
    window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer");
  }

  return (
    <main className="min-h-screen bg-[#fffdfb] text-[#241b18]">
      <div className="bg-[#f00024] px-5 py-2 text-center text-xs font-bold tracking-wide text-white sm:text-sm">Pago en línea con Nequi, PSE o tarjeta · También atendemos por WhatsApp</div>
      <header className="sticky top-0 z-40 border-b border-orange-100 bg-white/95 backdrop-blur">
        <div className="mx-auto flex min-h-24 max-w-7xl items-center justify-between gap-4 px-5 py-3 lg:px-8">
          <a href="#inicio" aria-label="Ir al inicio"><Image src="/brand/nutrimax-logo-transparent.png" width={300} height={113} alt="Alimentos Nutrimax" className="h-16 w-auto sm:h-[4.5rem]" priority /></a>
          <nav className="hidden items-center gap-5 text-sm font-extrabold lg:flex"><a href="/quienes-somos" className="hover:text-[#ff0026]">QUIÉNES SOMOS</a><a href="/productos" className="hover:text-[#ff0026]">PRODUCTOS</a><a href="/tienda" className="hover:text-[#ff0026]">TIENDA</a><a href="/recetas" className="hover:text-[#ff0026]">RECETAS</a><a href="/recetario-desayunos-proteicos" className="font-black text-[#ef1723]">RECETARIO DIGITAL</a><a href="/contactanos" className="rounded-full bg-[#ff7200] px-4 py-2 text-white shadow-md hover:bg-[#e85f00]">CONTÁCTANOS</a></nav>
          <div className="flex items-center gap-2">
            <button onClick={() => setCartOpen(true)} className="relative flex h-11 items-center gap-2 rounded-full bg-[#ef1723] px-4 font-bold text-white shadow-sm hover:bg-[#c80d17]" aria-label={`Abrir carrito y pagar; ${quantity} productos`}><ShoppingBag size={19} /><span>Carrito y pago</span>{quantity > 0 && <span className="grid min-w-6 place-items-center rounded-full bg-white px-1.5 py-0.5 text-xs text-[#ef1723]">{quantity}</span>}</button>
            <button onClick={() => setMenuOpen(!menuOpen)} className="grid h-11 w-11 place-items-center rounded-full border border-red-100 lg:hidden" aria-label="Abrir menú"><Menu size={21} /></button>
          </div>
        </div>
        {menuOpen && <nav className="grid gap-1 border-t border-red-100 bg-white p-4 text-lg font-bold lg:hidden"><a href="/quienes-somos" className="p-3">Quiénes somos</a><a href="/productos" className="p-3">Productos</a><a href="/tienda" className="p-3">Tienda</a><a href="/recetas" className="p-3">Recetas</a><a href="/recetario-desayunos-proteicos" className="p-3 text-[#ef1723]">Recetario digital</a><a href="/contactanos" className="p-3">Contáctanos</a></nav>}
      </header>

      <section id="inicio" className="relative overflow-hidden bg-[linear-gradient(115deg,#e90022_0%,#ff0a2d_50%,#ff7900_100%)] text-white">
        <div className="absolute -left-24 top-20 h-72 w-72 rounded-full bg-orange-300/20 blur-3xl"/><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_center,rgba(255,213,140,.35),transparent_60%)]"/>
        <div className="relative mx-auto grid min-h-[610px] max-w-7xl items-center gap-8 px-5 py-14 lg:grid-cols-[.9fr_1.1fr] lg:px-8">
          <div className="z-10"><span className="inline-flex rounded-full border border-white/30 bg-white/15 px-4 py-2 text-sm font-extrabold backdrop-blur">Alimentos Nutrimax · Bogotá</span><h1 className="mt-6 max-w-xl text-5xl font-black leading-[.94] tracking-[-.05em] sm:text-6xl lg:text-7xl">Desayunos con más sabor, todos los días.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-red-50">Granolas crocantes en presentaciones para disfrutar, compartir y llevar a tu negocio.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#productos" className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 font-black text-[#c80d17] shadow-lg">Elegir productos <ChevronRight size={18}/></a><button onClick={() => setCartOpen(true)} className="inline-flex items-center gap-2 rounded-full bg-[#241b18] px-6 py-3.5 font-black text-white shadow-lg"><CreditCard size={19}/> Pagar en línea</button><a href={`https://wa.me/${whatsappNumber}`} target="_blank" rel="noreferrer" className="rounded-full border-2 border-white px-6 py-3 font-black text-white">WhatsApp</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-white/90"><span className="flex items-center gap-2"><Check size={18}/> Elaboración colombiana</span><span className="flex items-center gap-2"><Check size={18}/> Pagos seguros con Wompi</span></div></div>
          <div className="relative mx-auto h-[430px] w-full max-w-[620px] sm:h-[520px]"><div className="absolute inset-x-14 bottom-5 h-20 rounded-[50%] bg-red-950/35 blur-2xl"/><Image src="/products/granola-gourmet-1500g.webp" width={960} height={1280} alt="Granola Gourmet Nutrimax de 1.500 gramos" className="absolute bottom-0 right-[3%] h-[92%] w-auto rotate-[4deg] object-contain drop-shadow-2xl" priority/><div className="absolute left-[2%] top-[15%] w-[48%] overflow-hidden rounded-full border-[10px] border-white shadow-2xl"><Image src="/products/granola-bowl.webp" width={700} height={700} alt="Granola Nutrimax lista para disfrutar" className="aspect-square w-full object-cover"/></div><div className="absolute bottom-8 left-[4%] rounded-2xl bg-[#ff8a16] px-5 py-4 shadow-xl"><p className="text-xs font-black uppercase tracking-wider">Granola Gourmet</p><p className="text-2xl font-black">1.500 g</p></div></div>
        </div>
      </section>

      <section className="border-b border-orange-100 bg-white"><div className="mx-auto grid max-w-7xl divide-y divide-orange-100 px-5 sm:grid-cols-3 sm:divide-x sm:divide-y-0 lg:px-8"><div className="flex items-center gap-4 py-6 sm:px-5"><MessageCircle className="text-[#ef1723]"/><div><p className="font-black">Atención directa</p><p className="text-sm text-[#74615a]">Resolvemos tus dudas por WhatsApp</p></div></div><div className="flex items-center gap-4 py-6 sm:px-5"><ShieldCheck className="text-[#e76712]"/><div><p className="font-black">Compra a tu manera</p><p className="text-sm text-[#74615a]">En línea o con asesoría personal</p></div></div><div className="flex items-center gap-4 py-6 sm:px-5"><Store className="text-[#ef1723]"/><div><p className="font-black">Precios mayoristas</p><p className="text-sm text-[#74615a]">Opciones especiales para negocios</p></div></div></div></section>

      <section id="premium" className="bg-[#fff7ef] py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="text-center"><p className="text-sm font-black uppercase tracking-[.2em] text-[#e45f0d]">Explora Nutrimax</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Una presentación para cada ocasión</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3"><a href="#productos" className="group relative min-h-80 overflow-hidden rounded-[2rem] bg-[#c80d17] p-7 text-white"><Image src="/products/granola-clasica-1500g.webp" width={600} height={800} alt="Granola clásica" className="absolute -bottom-24 right-[-10%] h-[115%] w-auto rotate-6 object-contain opacity-85 transition duration-500 group-hover:scale-105"/><div className="relative z-10"><p className="text-sm font-black uppercase tracking-wider text-red-100">Para compartir</p><h3 className="mt-2 text-3xl font-black">Clásica</h3><span className="mt-4 inline-flex items-center gap-1 font-bold">Ver producto <ChevronRight size={18}/></span></div></a><a href="#productos" className="group relative min-h-80 overflow-hidden rounded-[2rem] bg-[#f47618] p-7 text-white"><Image src="/products/granola-gourmet-1500g.webp" width={600} height={800} alt="Granola gourmet" className="absolute -bottom-24 right-[-10%] h-[115%] w-auto -rotate-3 object-contain opacity-90 transition duration-500 group-hover:scale-105"/><div className="relative z-10"><p className="text-sm font-black uppercase tracking-wider text-orange-50">Mezcla especial</p><h3 className="mt-2 text-3xl font-black">Gourmet</h3><span className="mt-4 inline-flex items-center gap-1 font-bold">Ver producto <ChevronRight size={18}/></span></div></a><a href="#productos" className="group relative min-h-80 overflow-hidden rounded-[2rem] bg-[#37211a] p-7 text-white"><Image src="/products/granola-premium-340g.webp" width={600} height={800} alt="Granola premium en tarro" className="absolute -bottom-20 right-[-8%] h-[110%] w-auto object-contain opacity-90 transition duration-500 group-hover:scale-105"/><div className="relative z-10"><p className="text-sm font-black uppercase tracking-wider text-orange-200">Lista para llevar</p><h3 className="mt-2 text-3xl font-black">Premium</h3><span className="mt-4 inline-flex items-center gap-1 font-bold">Ver producto <ChevronRight size={18}/></span></div></a></div></div></section>

      <section id="productos" className="bg-white py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="text-sm font-black uppercase tracking-[.18em] text-[#ef1723]">Productos destacados</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Elige tu granola Nutrimax</h2><p className="mt-4 text-lg text-[#675752]">Agrega tus favoritas y finaliza el pedido fácilmente.</p></div><span className="w-fit rounded-full bg-orange-50 px-4 py-2 text-sm font-black text-[#d65a0c]">5 presentaciones disponibles</span></div><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">
        {products.map((product) => <article key={product.id} className="group overflow-hidden rounded-3xl border border-[#eaded9] bg-[#fffdfb] shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="overflow-hidden bg-[#f6eeea]"><Image src={product.image} width={720} height={900} alt={`${product.name}, ${product.size}`} className="aspect-[4/5] w-full object-cover transition duration-500 group-hover:scale-[1.03]" /></div><div className="p-5"><p className="text-sm font-bold text-[#ef1723]">{product.size}</p><h3 className="mt-1 text-xl font-black leading-tight">{product.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-[#6d5c56]">{product.note}</p><a href={`/productos/${product.id}`} className="mt-3 inline-flex font-bold text-[#d65a0c] underline decoration-orange-200 underline-offset-4">Ver ingredientes y tabla</a><p className="mt-4 text-2xl font-black">{money.format(product.price)}</p>{(cart[product.id] ?? 0) === 0 ? <button onClick={() => change(product.id, 1)} className="mt-4 w-full rounded-full bg-[#ef1723] py-3 font-bold text-white hover:bg-[#c80d17]">Agregar al pedido</button> : <div className="mt-4 flex items-center justify-between rounded-full border-2 border-red-100 p-1"><button onClick={() => change(product.id, -1)} className="grid h-10 w-10 place-items-center rounded-full hover:bg-red-50" aria-label={`Quitar una unidad de ${product.name}`}><Minus size={18}/></button><span className="font-black">{cart[product.id]}</span><button onClick={() => change(product.id, 1)} className="grid h-10 w-10 place-items-center rounded-full bg-[#ef1723] text-white" aria-label={`Agregar una unidad de ${product.name}`}><Plus size={18}/></button></div>}</div></article>)}
      </div></div></section>

      <section id="nosotros" className="bg-[linear-gradient(120deg,#3c1d14,#a20d14)] py-20 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div className="p-4 sm:p-8"><p className="text-sm font-black uppercase tracking-[.18em] text-orange-300">Alimentos Nutrimax</p><h2 className="mt-3 max-w-2xl text-4xl font-black tracking-tight sm:text-5xl">Productos hechos para disfrutar y compartir.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-orange-50/90">Somos una empresa colombiana dedicada a elaborar alimentos con sabor, calidad y una atención cercana a cada cliente.</p></div><div id="mayoristas" className="rounded-[2rem] bg-white p-8 text-[#241b18] shadow-2xl sm:p-12"><p className="text-sm font-black uppercase tracking-[.18em] text-[#e76712]">Sé nuestro aliado</p><h2 className="mt-3 text-3xl font-black">¿Tienes una tienda o supermercado?</h2><p className="mt-4 leading-7 text-[#675752]">Conoce nuestras presentaciones, cantidades mínimas y precios especiales para negocios.</p><a href={`https://wa.me/${whatsappNumber}?text=${encodeURIComponent("Hola, Alimentos Nutrimax. Deseo información sobre precios y pedidos mayoristas.")}`} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#ef1723] px-6 py-3.5 font-black text-white">Consultar precios mayoristas <ChevronRight size={18}/></a></div></div></section>
      <footer className="border-t border-[#eaded9] bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-[#675752] sm:flex-row sm:items-center sm:justify-between lg:px-8"><Image src="/brand/nutrimax-logo-transparent.png" width={170} height={64} alt="Nutrimax" className="h-9 w-auto"/><p>Pedidos: 300 616 0613 · Bogotá, Colombia</p></div></footer>

      {cartOpen && <div className="fixed inset-0 z-50 bg-black/40" onClick={() => setCartOpen(false)}><aside className="ml-auto flex h-full w-full max-w-md flex-col bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Tu pedido</h2><button onClick={() => setCartOpen(false)} className="grid h-10 w-10 place-items-center rounded-full bg-[#f8efeb]" aria-label="Cerrar carrito"><X/></button></div>{items.length === 0 ? <div className="grid flex-1 place-items-center text-center"><div><ShoppingBag className="mx-auto text-[#ef1723]" size={42}/><p className="mt-4 text-lg font-bold">Tu pedido está vacío</p><p className="mt-2 text-[#675752]">Agrega una granola para comenzar.</p></div></div> : <><div className="mt-6 flex-1 space-y-4 overflow-y-auto">{items.map((product) => <div key={product.id} className="flex gap-4 rounded-2xl border border-[#eaded9] p-3"><Image src={product.image} width={76} height={86} alt="" className="h-20 w-16 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="font-bold">{product.name}</p><p className="text-sm text-[#675752]">{product.size}</p><div className="mt-2 flex items-center gap-3"><button onClick={() => change(product.id,-1)} className="rounded-full bg-[#f8efeb] p-1"><Minus size={16}/></button><span className="font-bold">{cart[product.id]}</span><button onClick={() => change(product.id,1)} className="rounded-full bg-[#f8efeb] p-1"><Plus size={16}/></button><span className="ml-auto font-black">{money.format(product.price * cart[product.id])}</span></div></div></div>)}</div><div className="border-t border-[#eaded9] pt-5"><div className="flex justify-between text-xl font-black"><span>Total productos</span><span>{money.format(total)}</span></div><div className="mt-3 rounded-2xl bg-orange-50 p-3 text-sm leading-5 text-[#7a3b0b]"><strong>Antes de pagar:</strong> confirma por WhatsApp la disponibilidad y el valor del domicilio. Luego ingresa en Wompi el total confirmado.</div><button onClick={sendWhatsApp} className="mt-5 w-full rounded-full bg-[#20a957] py-3.5 font-black text-white">1. Confirmar pedido y domicilio</button><a href={paymentLink} target="_blank" rel="noopener noreferrer" className="mt-3 block w-full rounded-full bg-[#241b18] py-3.5 text-center font-black text-white transition hover:bg-black">2. Pagar con Nequi, PSE o tarjeta</a><p className="mt-2 text-center text-xs text-[#675752]">Pago seguro procesado por Wompi</p></div></>}</aside></div>}
    </main>
  );
}
