"use client";
import Image from "next/image";
import { CreditCard, MessageCircle } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { SiteFooter, SiteHeader } from "@/components/site-header";
import { products } from "@/lib/products";
const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const paymentLink="https://checkout.nequi.wompi.co/l/Z801LL";
export default function StorePage(){return <main className="bg-[#fffaf6] text-[#241b18]"><SiteHeader/><PageHero eyebrow="Tienda Nutrimax" title="Compra tu granola favorita." text="Elige tu producto, confirma el domicilio y paga en línea con Nequi, PSE o tarjeta."/><section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="mb-8 rounded-3xl border border-orange-200 bg-orange-50 p-5 text-[#743509]"><p className="font-black">¿Cómo comprar?</p><p className="mt-1">Confirma primero el valor del domicilio por WhatsApp. Después utiliza el botón <strong>Pagar en línea</strong> e ingresa en Wompi el total confirmado.</p></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.map(p=>{const text=encodeURIComponent(`Hola, Alimentos Nutrimax. Deseo comprar ${p.name} ${p.size} por ${money.format(p.price)}. Quiero confirmar disponibilidad y valor del domicilio.`);return <article key={p.slug} className="overflow-hidden rounded-3xl border border-orange-100 bg-white shadow-sm"><Image unoptimized src={p.image} width={720} height={800} alt={`${p.name} ${p.size}`} className="aspect-square w-full object-cover"/><div className="p-6"><p className="font-bold text-[#ef1723]">{p.size}</p><h2 className="mt-1 text-2xl font-black">{p.name}</h2><p className="mt-4 text-3xl font-black">{money.format(p.price)}</p><div className="mt-5 grid gap-2"><a href={paymentLink} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#241b18] px-5 py-3 font-black text-white"><CreditCard size={18}/> Pagar en línea</a><a href={`https://wa.me/573006160613?text=${text}`} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#20a957] px-5 py-3 font-black text-white"><MessageCircle size={18}/> Confirmar por WhatsApp</a><a href={`/productos/${p.slug}`} className="mt-1 text-center font-black text-[#ef1723] underline decoration-red-200 underline-offset-4">Ver detalles</a></div></div></article>})}</div></section><SiteFooter/></main>}
